FROM ghcr.io/containerpak/mesa64-sdk:main

ARG DEBIAN_FRONTEND=noninteractive
ARG CPAK_ARCH=amd64

RUN apt-get update && \
    apt-get install -y \
        mesa-utils \
        mesa-utils-extra \
        vulkan-tools && \
    if [ "${CPAK_ARCH}" = amd64 ]; then \
        dpkg --add-architecture i386 && \
        apt-get update && \
        apt-get install -y \
            libc6-i386 \
            libegl1:i386 \
            libgl1:i386 \
            libgl1-mesa-dri:i386 \
            libwayland-egl1:i386 \
            mesa-vulkan-drivers:i386; \
    fi && \
    cpak-clean-junk
