FROM ghcr.io/containerpak/base-sdk:main
#FROM cpak/base-sdk

RUN apt install -y \    
    libegl-mesa0 \
    libglx-mesa0 libglx-mesa0:i386 \
    libwayland-egl1 \
    libgl1:i386 \
    libgl1-mesa-dri libgl1-mesa-dri:i386 \
    libvulkan1 mesa-vulkan-drivers vulkan-tools \
    mesa-utils mesa-utils-extra \
    libc6-i386 \
    libegl1-mesa-dev \
    libgles2-mesa-dev \
    libgl1-mesa-dev \
    libvulkan-dev \
    libglvnd-dev \
    mesa-common-dev \
    libglx-dev