FROM ghcr.io/containerpak/mesa64:main

ARG DEBIAN_FRONTEND=noninteractive

RUN dpkg --add-architecture i386 && \
    apt-get update && \
    apt-get install -y \
        libc6-i386 \
        libegl1:i386 \
        libgl1:i386 \
        libgl1-mesa-dri:i386 \
        libwayland-egl1:i386 \
        mesa-vulkan-drivers:i386 && \
    cpak-clean-junk
