FROM ghcr.io/containerpak/mesa64-sdk:main

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y \
        libadwaita-1-dev \
        libgtk-4-dev && \
    cpak-clean-junk
