FROM ghcr.io/containerpak/base:main
#FROM cpak/base

ARG DEBIAN_FRONTEND=noninteractive

RUN apt install -y \    
    libegl-mesa0 \
    libglx-mesa0 libglx-mesa0:i386 \
    libwayland-egl1 \
    libgl1:i386 \
    libgl1-mesa-dri libgl1-mesa-dri:i386 \
    libvulkan1 mesa-vulkan-drivers vulkan-tools \
    mesa-utils mesa-utils-extra \
    libc6-i386