APT::Install-Recommends "false";
APT::Install-Suggests "false";
APT::Keep-Downloaded-Packages "false";
Acquire::Languages "none";
Dir::Cache::pkgcache "";
Dir::Cache::srcpkgcache "";

DPkg::Options {
    "--path-exclude=/usr/share/app-info/*";
    "--path-exclude=/usr/share/bug/*";
    "--path-exclude=/usr/share/doc/*";
    "--path-include=/usr/share/doc/*/copyright";
    "--path-exclude=/usr/share/doc-base/*";
    "--path-exclude=/usr/share/gtk-doc/*";
    "--path-exclude=/usr/share/help/*";
    "--path-exclude=/usr/share/info/*";
    "--path-exclude=/usr/share/lintian/*";
    "--path-exclude=/usr/share/man/*";
    "--path-exclude=/usr/share/metainfo/*";
};
