#!/bin/sh

set -eu

apt-get clean
rm -rf /var/lib/apt/lists/*
rm -rf /var/cache/apt/archives/*.deb /var/cache/apt/*.bin
rm -rf /var/cache/debconf/*-old /var/lib/dpkg/*-old
rm -rf /var/log/apt/* /var/log/dpkg.log /var/log/alternatives.log
rm -rf /usr/share/app-info/* /usr/share/bug/* /usr/share/doc-base/*
rm -rf /usr/share/gtk-doc/* /usr/share/help/* /usr/share/info/*
rm -rf /usr/share/lintian/* /usr/share/man/* /usr/share/metainfo/*
find /usr/share/doc -type f ! -name copyright -delete
find /usr/share/doc -depth -type d -empty -delete
rm -rf /tmp/* /var/tmp/*
mkdir -p /var/lib/apt/lists/partial
mkdir -p /var/cache/apt/archives/partial
mkdir -p /var/log/apt
mkdir -p /usr/share/man/man1
