FROM ghcr.io/containerpak/mesa:main
#FROM cpak/mesa

ARG DEBIAN_FRONTEND=noninteractive

RUN apt install -y libgtk-4-1 libadwaita-1-0 libwebkit2gtk-4.1-0 libgweather-4-0 \
    dbus libdbus-1-3 libwayland-cursor0 librsvg2-2 fonts-noto
