FROM ubuntu:23.04

RUN echo '#!/bin/bash' > /usr/bin/cpak-clean-junk && \
    echo 'set -e' >> /usr/bin/cpak-clean-junk && \
    echo 'export DEBIAN_FRONTEND=noninteractive' >> /usr/bin/cpak-clean-junk && \
    echo 'apt clean' >> /usr/bin/cpak-clean-junk && \
    echo 'apt autoremove -y' >> /usr/bin/cpak-clean-junk && \
    echo 'rm -rf /var/cache/*' >> /usr/bin/cpak-clean-junk && \
    echo 'rm -rf /var/log' >> /usr/bin/cpak-clean-junk && \
    echo 'rm -rf /var/tmp/*' >> /usr/bin/cpak-clean-junk && \
    echo 'rm -rf /tmp/*' >> /usr/bin/cpak-clean-junk && \
    echo 'mkdir -p /var/cache/apt/archives/partial' >> /usr/bin/cpak-clean-junk && \
    chmod +x /usr/bin/cpak-clean-junk
