FROM ghcr.io/containerpak/base:main
ARG DEBIAN_FRONTEND=noninteractive
RUN dpkg --add-architecture i386 && \
    apt update && \
    apt install -y \
    libegl1-mesa libgl1-mesa-glx libwayland-egl1-mesa libvulkan1 mesa-vulkan-drivers mesa-utils mesa-utils-extra libc6-i386 \
    libgl1-mesa-dri:i386 libgl1:i386 libgl1-mesa-glx:i386 && \
    mesa-vulkan-drivers &&\
    /usr/bin/cpak-clean-junk
