FROM ghcr.io/containerpak/base:main
ARG DEBIAN_FRONTEND=noninteractive
RUN dpkg --add-architecture i386
RUN apt update
RUN apt install -y libegl1-mesa libgl1-mesa-glx libwayland-egl1-mesa libvulkan1 mesa-vulkan-drivers mesa-utils mesa-utils-extra libc6:i386