name: Build and publish

on:
  workflow_dispatch: {}
  push:
    branches: [main]
    paths:
      - '.github/workflows/docker-publish.yml'
      - 'platform/**'
      - 'sdk/**'
  schedule:
    - cron: '0 3 * * 1'

env:
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: read
  packages: write

jobs:
  build_base:
    runs-on: ubuntu-latest
    container:
      image: quay.io/podman/stable@sha256:663e0dbf407987b7db3f20d3588c283a8228db17b282d2029a482d4d47e36964
      options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Login to GHCR
        run: echo "${{ env.REGISTRY_PASSWORD }}" | podman login ghcr.io --username "${{ env.REGISTRY_USER }}" --password-stdin

      - name: SDK Base
        run: |
          cd sdk
          podman build --format oci -f base/Containerfile --tag ghcr.io/containerpak/base-sdk:main .
          podman push --format oci --compression-format zstd:chunked --force-compression "ghcr.io/containerpak/base-sdk:main"

      - name: Platform Base
        run: |
          cd platform
          podman build --format oci -f base/Containerfile --tag ghcr.io/containerpak/base:main .
          podman push --format oci --compression-format zstd:chunked --force-compression "ghcr.io/containerpak/base:main"
          sleep 10

  build_mesa:
    needs: build_base
    runs-on: ubuntu-latest
    container:
      image: quay.io/podman/stable@sha256:663e0dbf407987b7db3f20d3588c283a8228db17b282d2029a482d4d47e36964
      options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Login to GHCR
        run: echo "${{ env.REGISTRY_PASSWORD }}" | podman login ghcr.io --username "${{ env.REGISTRY_USER }}" --password-stdin

      - name: SDK Mesa
        run: |
          cd sdk
          podman build --format oci -f mesa/Containerfile --tag ghcr.io/containerpak/mesa-sdk:main .
          podman push --format oci --compression-format zstd:chunked --force-compression "ghcr.io/containerpak/mesa-sdk:main"

      - name: Platform Mesa
        run: |
          cd platform
          podman build --format oci -f mesa/Containerfile --tag ghcr.io/containerpak/mesa:main .
          podman push --format oci --compression-format zstd:chunked --force-compression "ghcr.io/containerpak/mesa:main"
          sleep 10

  build_gtk:
    needs: build_mesa
    runs-on: ubuntu-latest
    container:
      image: quay.io/podman/stable@sha256:663e0dbf407987b7db3f20d3588c283a8228db17b282d2029a482d4d47e36964
      options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Login to GHCR
        run: echo "${{ env.REGISTRY_PASSWORD }}" | podman login ghcr.io --username "${{ env.REGISTRY_USER }}" --password-stdin

      - name: SDK GTK
        run: |
          cd sdk
          podman build --format oci -f gtk/Containerfile --tag ghcr.io/containerpak/gtk-sdk:main .
          podman push --format oci --compression-format zstd:chunked --force-compression "ghcr.io/containerpak/gtk-sdk:main"

      - name: Platform GTK
        run: |
          cd platform
          podman build --format oci -f gtk/Containerfile --tag ghcr.io/containerpak/gtk:main .
          podman push --format oci --compression-format zstd:chunked --force-compression "ghcr.io/containerpak/gtk:main"
          sleep 10
